version: "3.9"
services:
  db:
    env_file:
      - ../config/.dev.env
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENV=dev
    volumes:
      - {{cookiecutter.project_slug}}_pgdata:/var/lib/postgresql/data
  web:
    env_file:
      - ../config/.dev.env
    build: ./web/
    entrypoint: ["sh", "/web/scripts/dev.entrypoint.sh"]
    volumes:
      - ../{{cookiecutter.project_slug}}:/{{cookiecutter.project_slug}}
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENV=dev
    depends_on:
      - db

volumes:
  {{cookiecutter.project_slug}}_pgdata: